version: '3.9'

services:
  flask:
    container_name: flask
    build: .
    ports:
    - 8080:5000
    volumes:
    - ./:/app
    environment:
    - FLASK_ENV=development
    depends_on:
    - psql_
    - redis_
    networks:
    - flaskNet

  psql_:
    container_name: psql_
    image: postgres
    ports:
    - 5432:5432
    volumes:
    - flaskDbVol:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=secret
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
    networks:
    - flaskNet

  redis_:
    container_name: redis_
    image: redis:6-alpine
    ports:
    - 6379:6379
    networks:
      - flaskNet

networks:
  flaskNet:
    driver: "bridge"


volumes:
  flaskDbVol:
    driver: local
